version: 2

builds:
  - env:
      - CGO_ENABLED=0
    binary: shotty
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s -X main.version={{.Version}}

archives:
  - name_template: >-
      {{ .Binary }}_{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "📖 Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "🔧 Maintenance"
      regexp: '^.*?(ci|build|chore|refactor|style)(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^Merge"

release:
  prerelease: "false"
  header: |
    ## What's Changed in {{ .Tag }}

    Full changelog: https://github.com/vdemeester/shotty/compare/{{ .PreviousTag }}...{{ .Tag }}
  footer: |
    ---
    **Full Changelog**: https://github.com/vdemeester/shotty/compare/{{ .PreviousTag }}...{{ .Tag }}
